// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'scores.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_ScoreModel _$ScoreModelFromJson(Map<String, dynamic> json) => _ScoreModel(
  gpax: (json['GPAX'] as num?)?.toDouble(),
  gpaTHAI: (json['GPA_THAI'] as num?)?.toDouble(),
  gpaMATH: (json['GPA_MATH'] as num?)?.toDouble(),
  gpaSCIENCE: (json['GPA_SCIENCE'] as num?)?.toDouble(),
  gpaSOCIAL: (json['GPA_SOCIAL'] as num?)?.toDouble(),
  gpaPE: (json['GPA_PE'] as num?)?.toDouble(),
  gpaART: (json['GPA_ART'] as num?)?.toDouble(),
  gpaKANNGAN: (json['GPA_KANNGAN'] as num?)?.toDouble(),
  gpaFOREIGNLANG: (json['GPA_FOREIGNLANG'] as num?)?.toDouble(),
  tgat: (json['TGAT'] as num?)?.toDouble(),
  tgat1: (json['TGAT1'] as num?)?.toDouble(),
  tgat2: (json['TGAT2'] as num?)?.toDouble(),
  tgat3: (json['TGAT3'] as num?)?.toDouble(),
  tpat1: (json['TPAT1'] as num?)?.toDouble(),
  tpat2: (json['TPAT2'] as num?)?.toDouble(),
  tpat3: (json['TPAT3'] as num?)?.toDouble(),
  tpat4: (json['TPAT4'] as num?)?.toDouble(),
  tpat5: (json['TPAT5'] as num?)?.toDouble(),
  tpat21: (json['TPAT21'] as num?)?.toDouble(),
  tpat22: (json['TPAT22'] as num?)?.toDouble(),
  tpat23: (json['TPAT23'] as num?)?.toDouble(),
  aLavelMATH1: (json['A_Level_MATH1'] as num?)?.toDouble(),
  aLavelMATH2: (json['A_Level_MATH2'] as num?)?.toDouble(),
  aLavelSCIENCE: (json['A_Level_SCIENCE'] as num?)?.toDouble(),
  aLavelPHY: (json['A_Level_PHY'] as num?)?.toDouble(),
  aLavelCHEM: (json['A_Level_CHEM'] as num?)?.toDouble(),
  aLavelBIO: (json['A_Level_BIO'] as num?)?.toDouble(),
  aLavelSOCIAL: (json['A_Level_SOCIAL'] as num?)?.toDouble(),
  aLavelTHAI: (json['A_Level_THAI'] as num?)?.toDouble(),
  aLavelENG: (json['A_Level_ENG'] as num?)?.toDouble(),
  aLavelFRANCE: (json['A_Level_FRANCE'] as num?)?.toDouble(),
  aLavelGERMAN: (json['A_Level_GERMAN'] as num?)?.toDouble(),
  aLavelJAPANESE: (json['A_Level_JAPANESE'] as num?)?.toDouble(),
  aLavelCHINESE: (json['A_Level_CHINESE'] as num?)?.toDouble(),
  aLavelBALI: (json['A_Level_BALI'] as num?)?.toDouble(),
  aLavelKOREAN: (json['A_Level_KOREAN'] as num?)?.toDouble(),
  aLavelSPAIN: (json['A_Level_SPAIN'] as num?)?.toDouble(),
);

Map<String, dynamic> _$ScoreModelToJson(_ScoreModel instance) =>
    <String, dynamic>{
      'GPAX': instance.gpax,
      'GPA_THAI': instance.gpaTHAI,
      'GPA_MATH': instance.gpaMATH,
      'GPA_SCIENCE': instance.gpaSCIENCE,
      'GPA_SOCIAL': instance.gpaSOCIAL,
      'GPA_PE': instance.gpaPE,
      'GPA_ART': instance.gpaART,
      'GPA_KANNGAN': instance.gpaKANNGAN,
      'GPA_FOREIGNLANG': instance.gpaFOREIGNLANG,
      'TGAT': instance.tgat,
      'TGAT1': instance.tgat1,
      'TGAT2': instance.tgat2,
      'TGAT3': instance.tgat3,
      'TPAT1': instance.tpat1,
      'TPAT2': instance.tpat2,
      'TPAT3': instance.tpat3,
      'TPAT4': instance.tpat4,
      'TPAT5': instance.tpat5,
      'TPAT21': instance.tpat21,
      'TPAT22': instance.tpat22,
      'TPAT23': instance.tpat23,
      'A_Level_MATH1': instance.aLavelMATH1,
      'A_Level_MATH2': instance.aLavelMATH2,
      'A_Level_SCIENCE': instance.aLavelSCIENCE,
      'A_Level_PHY': instance.aLavelPHY,
      'A_Level_CHEM': instance.aLavelCHEM,
      'A_Level_BIO': instance.aLavelBIO,
      'A_Level_SOCIAL': instance.aLavelSOCIAL,
      'A_Level_THAI': instance.aLavelTHAI,
      'A_Level_ENG': instance.aLavelENG,
      'A_Level_FRANCE': instance.aLavelFRANCE,
      'A_Level_GERMAN': instance.aLavelGERMAN,
      'A_Level_JAPANESE': instance.aLavelJAPANESE,
      'A_Level_CHINESE': instance.aLavelCHINESE,
      'A_Level_BALI': instance.aLavelBALI,
      'A_Level_KOREAN': instance.aLavelKOREAN,
      'A_Level_SPAIN': instance.aLavelSPAIN,
    };
