final Map<String, String> itemNameMap = {
  'GPAX': 'GPAX',
  'GPA_THAI': 'GPA ไทย',
  'GPA_MATH': 'GPA คณิตศาสตร์',
  'GPA_SCIENCE': 'GPA SCIENCE',
  'GPA_SOCIAL': 'GPA SOCIAL',
  'GPA_PE': 'GPA PE',
  'GPA_ART': 'GPA ART',
  'GPA_KANNGAN': 'GPA การงาน',
  'GPA_FOREIGNLANG': 'GPA ภาษาต่างประเทศ',
  'TGAT1': 'TGAT1',
  'TGAT2': 'TGAT2',
  'TGAT3': 'TGAT3',
  'TPAT1': 'TPAT1',
  'TPAT3': 'TPAT3',
  'TPAT4': 'TPAT4',
  'TPAT5': 'TPAT5',
  'TPAT21': 'TPAT21',
  'TPAT22': 'TPAT22',
  'TPAT23': 'TPAT23',
  'A_Level_MATH1': 'A Level MATH1',
  'A_Level_MATH2': 'A Level MATH2',
  'A_Level_SCIENCE': 'A Level SCIENCE',
  'A_Level_PHY': 'A Level PHY',
  'A_Level_CHEM': 'A Level CHEM',
  'A_Level_BIO': 'A Level BIO',
  'A_Level_SOCIAL': 'A Level SOCIAL',
  'A_Level_THAI': 'A Level THAI',
  'A_Level_ENG': 'A Level ENG',
  'A_Level_FRANCE': 'A Level FRANCE',
  'A_Level_GERMAN': 'A Level GERMAN',
  'A_Level_JAPANESE': 'A Level JAPANESE',
  'A_Level_CHINESE': 'A Level CHINESE',
  'A_Level_BALI': 'A Level BALI',
  'A_Level_KOREAN': 'A Level KOREAN',
  'A_Level_SPAIN': 'A Level SPAIN',
};
